owner = 'tjdwill'

[2c358220-dfb7-47f8-8500-d3e9e1af9538]
description = 'The second test account in the book'
isActive = true
name = 'TestAccount2'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-5.00'
    notes = 'Transaction #5'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298777416+0000'
    transactionId = '318cf86b-7a79-4a1c-aea4-6dea0788c7a3'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-7.00'
    notes = 'Transaction #7'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298786682+0000'
    transactionId = '4c9fdea7-ba0c-45cc-8f66-240980c37d5c'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-9.00'
    notes = 'Transaction #9'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.300354596+0000'
    transactionId = '5b96c1ad-46ba-4366-8241-fbc1cd0e9bbd'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-4.00'
    notes = 'Transaction #4'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298772941+0000'
    transactionId = '5c2edfcc-3b1f-4a4c-9ca9-52248d7d3901'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-6.00'
    notes = 'Transaction #6'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298782000+0000'
    transactionId = '6919ceca-add4-40e0-ab4b-a1f58809f080'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-2.00'
    notes = 'Transaction #2'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298761041+0000'
    transactionId = 'a1545928-1195-40b9-b3c4-78f837012afb'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-3.00'
    notes = 'Transaction #3'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298768396+0000'
    transactionId = 'aae408f5-52e6-4f1c-9894-417c59aa50cc'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '2000.00'
    notes = 'Initial Deposit'
    otherPartyId = '00000000-0000-0000-0000-000000000000'
    timeStamp = '2025-10-12 01:19:35.298743250+0000'
    transactionId = 'c4a84b47-1acd-4930-9f6d-008c10782dfe'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-8.00'
    notes = 'Transaction #8'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.300347022+0000'
    transactionId = 'c58960d9-4cac-4036-ad2e-1aef26946dae'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-1.00'
    notes = 'Transaction #1'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.298755828+0000'
    transactionId = 'e72a1ff5-e416-48ff-99ef-02f7fadabaf7'

    [[2c358220-dfb7-47f8-8500-d3e9e1af9538.transactions]]
    amount = '-10.00'
    notes = 'Transaction #10'
    otherPartyId = '5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5'
    timeStamp = '2025-10-12 01:19:35.300359367+0000'
    transactionId = 'fced3dbe-eec8-4979-aefd-686432f00d6c'

[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5]
description = 'The first test account in the book'
isActive = true
name = 'TestAccount1'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '5.00'
    notes = 'Transaction #5'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298777416+0000'
    transactionId = '318cf86b-7a79-4a1c-aea4-6dea0788c7a3'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '7.00'
    notes = 'Transaction #7'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298786682+0000'
    transactionId = '4c9fdea7-ba0c-45cc-8f66-240980c37d5c'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '9.00'
    notes = 'Transaction #9'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.300354596+0000'
    transactionId = '5b96c1ad-46ba-4366-8241-fbc1cd0e9bbd'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '4.00'
    notes = 'Transaction #4'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298772941+0000'
    transactionId = '5c2edfcc-3b1f-4a4c-9ca9-52248d7d3901'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '6.00'
    notes = 'Transaction #6'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298782000+0000'
    transactionId = '6919ceca-add4-40e0-ab4b-a1f58809f080'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '2.00'
    notes = 'Transaction #2'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298761041+0000'
    transactionId = 'a1545928-1195-40b9-b3c4-78f837012afb'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '3.00'
    notes = 'Transaction #3'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298768396+0000'
    transactionId = 'aae408f5-52e6-4f1c-9894-417c59aa50cc'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '5000.00'
    notes = 'Initial Deposit'
    otherPartyId = '00000000-0000-0000-0000-000000000000'
    timeStamp = '2025-10-12 01:19:35.298738713+0000'
    transactionId = 'ba4be2a1-2b09-444e-a368-f81825a6168c'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '8.00'
    notes = 'Transaction #8'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.300347022+0000'
    transactionId = 'c58960d9-4cac-4036-ad2e-1aef26946dae'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '1.00'
    notes = 'Transaction #1'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.298755828+0000'
    transactionId = 'e72a1ff5-e416-48ff-99ef-02f7fadabaf7'

    [[5cbb91d0-f69e-4e22-aefa-e1e7791fc3d5.transactions]]
    amount = '10.00'
    notes = 'Transaction #10'
    otherPartyId = '2c358220-dfb7-47f8-8500-d3e9e1af9538'
    timeStamp = '2025-10-12 01:19:35.300359367+0000'
    transactionId = 'fced3dbe-eec8-4979-aefd-686432f00d6c'
